### ISSUE TITLE
Can you share Grafana’s monitoring template?

### ISSUE THREAD

**Issue by uepuer** [leandromoreira/cdn-up-and-running#11]
Can you share Grafana’s monitoring template?
 I need this monitoring template,

 thank you!

**Comment by leandromoreira** [comment]
Hey @uepuer, I think they're stored at the [grafana.db](https://github.com/leandromoreira/cdn-up-and-running/blob/main/data/grafana/grafana.db). You can access them through a running instance as well.

**Comment by leandromoreira** [comment]
I believe it's a sqlite datastore, so you can read from it as well.

**Comment by uepuer** [comment]
O......,  I have installed using docker-compose and got the grafana json file, thank you again!
